services:
  mysql:
    image : mysql:8.0
    container_name : mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: countries
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin@123
    volumes:
      - ./mysql_data_new:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - twotierapllication
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-h","localhost","-uadmin","-pAdmin@123"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 15s

  django_app:
    build:
      context: .
    container_name : django_app
    environment:
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: countries
      DB_USER: admin
      DB_PASSWORD: Admin@123
      DB_HOST: mysql
      DB_PORT: 3306
    networks:
      - twotierapllication
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    restart: always

networks:
  twotierapllication:

volumes:
  mysql_data_new:



  

  

